### ISSUE TITLE
LensBlurEffect.LensBlurFocusAreaEdgeMirroring dont' work

### ISSUE THREAD

**Issue by JuniperPhoton** [Microsoft/Lumia-imaging-sdk#6]
I want there is a `smooth transition` between the focus area and the unfocus area.
However, whatever I try, the transition between those two area is `arbitrary`.

Here is my code:

```
//Draw a bitmap that contains a white circle in a black rect.
var bmp = new WriteableBitmap(canvasWidth, canvasHeight);
bmp.FillRectangle(0, 0, canvasWidth, canvasHeight, Colors.Black);
bmp.FillEllipseCentered((int)centerX, (int)centerY, (int)BlurCircle.ActualWidth/2, (int)BlurCircle.ActualHeight/2, Colors.White);

var src = new StorageFileImageSource(backgroundFile);
var masksrc = new BitmapImageSource((Bitmap)bmp.AsBitmap());
var blurEffect = new LensBlurEffect(src, masksrc);
blurEffect.FocusAreaEdgeMirroring = LensBlurFocusAreaEdgeMirroring.On;
blurEffect.FocusEdgeSoftening = new LensBlurFocusEdgeSoftening(30);
blurEffect.BlendKernelWidth = 255;
blurEffect.Kernels = new LensBlurPredefinedKernel[] { new LensBlurPredefinedKernel(LensBlurPredefinedKernelShape.Circle, 30) };

using(var renderer=new JpegRenderer(blurEffect)
{
      //...do render thing.
}
```

**Comment by davidbozjak** [comment]
Hi,

Have you given taken a look at the DepthOfField Extras? We realized that the smooth transition lens blur is an effect that is hard to achieve, so we created several samples to help developers. They can be found right here on GitHub, and will show you how to achieve a smooth transition between kernels and how to generate a mask with the SDK, without having to worry about the WriteableBitmap. 

For your case in particular we have written the EllipticFocusDepthOfFieldEffect (https://github.com/Microsoft/Lumia-imaging-sdk/blob/master/Extras/Lumia.Imaging.Extras.ImageProviders/Lumia.Imaging.Extras.ImageProviders.Shared/DepthOfField/EllipticFocusDepthOfFieldEffect.cs). You can use that as inspiration, or include it as source code in your application, or just use pieces of it!

Please take a look at the entire concepts, including tests: https://github.com/Microsoft/Lumia-imaging-sdk/tree/master/Extras/Lumia.Imaging.Extras.ImageProviders/Lumia.Imaging.Extras.ImageProviders.Shared/DepthOfField

As for your sample code in particular, I see two obvious shortcomings:
- You are using only one kernel. To achieve a smooth transition you will want to create several (10? Perhaps up to 25) increasingly large kernels, to achieve a gradual blur from your focus area.
- The blendKernelWidth parameter is much too large. We recommend setting it to 1/2 of the width of your largest kernel.

Please note that the size of the kernels themselves should also depend on the size of your image.

**Comment by JuniperPhoton** [comment]
Thanks for replying. EllipticFocusDepthOfFieldEffect does help :-D !
